JooleStoreApp/Controllers/SearchController.cs
using JooleStore_DAL;
using JooleStore_Service;
using JooleStoreApp.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace JooleStoreApp.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            if(Session["isLoggedIn"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost]
        public ActionResult OnSearch(FormCollection form) 
        {
                TempData["subcategoryId"] = form["subcategory"];
                //getting subcategoryid from search page
                int subcategoryId = int.Parse(Request.Form["subcategory"]);
                Service service = new Service();
                List<Product> list = service.getSubcategoryProducts(subcategoryId);
                List<ProductM> prodList = new List<ProductM>();

                foreach (Product prod in list)
                {
                    Dictionary<string, List<Tuple<int, string, string>>> properties = service.GetProductProperties(prod.ProductId);

                    List<Tuple<int, string, string>> techSpec = properties["techSpec"];
                    List<Tuple<int, string, string>> typeProp = properties["type"];
                    List<PropertyViewM> techSpec1 = new List<PropertyViewM>();
                    List<PropertyViewM> typeProp1 = new List<PropertyViewM>();
                    foreach (Tuple<int, string, string> tup in techSpec)
                    {
                        PropertyViewM vm = new PropertyViewM { Id = tup.Item1, Name = tup.Item2, Value = tup.Item3 };
                        techSpec1.Add(vm);
                    }
                    foreach (Tuple<int, string, string> tup in typeProp)
                    {
                        PropertyViewM vm = new PropertyViewM { Id = tup.Item1, Name = tup.Item2, Value = tup.Item3 };
                        typeProp1.Add(vm);
                    }
                    ProductM newProd = new ProductM
                    {
                        ManufacturerId = prod.ManufacturerId,
                        ProductId = prod.ProductId,
                        ProductImage = prod.ProductImage,
                        ProductName = prod.ProductName,
                        Series = prod.Series,
                        Model = prod.Model,
                        ModelYear = prod.ModelYear,
                        SubcategoryId = prod.SubcategoryId,
                        techSpec = techSpec1,
                        typeProp = typeProp1
                    };
                    prodList.Add(newProd);
                }

                List<tblTypeRange> list2 = service.getFilterType(subcategoryId);
                List<tblTypeRangeM> listFilterType = new List<tblTypeRangeM>();
                foreach (tblTypeRange type in list2)
                {
                    tblTypeRangeM newTypeFilter = new tblTypeRangeM
                    {
                        TypeName = type.TypeName,
                        TypeOptions = type.TypeOptions.Split(',')
                    };
                    listFilterType.Add(newTypeFilter);
                }

                List<tblTechSpecRange> list3 = service.getFilterTechSpec(subcategoryId);
                List<tblTechSpecRangeM> listFilterTechSpec = new List<tblTechSpecRangeM>();
                foreach (tblTechSpecRange type in list3)
                {
                    string propertyName = service.GetPropertyNameById(type.PropertyId);
                    tblTechSpecRangeM newTechSpecFilter = new tblTechSpecRangeM
                    {
                        MinValue = type.MinValue,
                        MaxValue = type.MaxValue,
                        PropertyId = type.PropertyId,
                        PropertyName = propertyName
                    };
                    listFilterTechSpec.Add(newTechSpecFilter);
                }

            if (Request.Form["isFilter"] == null)
            {
                SearchResultViewModel viewModel = new SearchResultViewModel
                {
                    Products = prodList,
                    TechSpecFilterList = listFilterTechSpec,
                    TypeRangeFilterList = listFilterType
                };
                return View("SearchResult", viewModel);
            }
            else {
                List<int> toRemove = new List<int>();
                for(int i=0; i< prodList.Count();i++) 
                {
                    foreach(PropertyViewM prop in prodList[i].typeProp) 
                    {
                        System.Diagnostics.Debug.WriteLine("Property value: "+prop.Value);
                        System.Diagnostics.Debug.WriteLine("Value from the form: " + Request.Form[prop.Name]);
                        if (!Request.Form[prop.Name].Equals("All")) {
                            if (!prop.Value.Equals(Request.Form[prop.Name]))
                            {
                                toRemove.Add(i);
                                break;
                            }
                        }
                    }
                    foreach (PropertyViewM prop in prodList[i].techSpec) 
                    {
                        
                        System.Diagnostics.Debug.WriteLine("Property value: " + prop.Value);
                        System.Diagnostics.Debug.WriteLine("Value from the form: " + Request.Form[prop.Name]);
                        if (int.Parse(prop.Value) > int.Parse(Request.Form[prop.Name])) 
                        {
                            toRemove.Add(i);
                            break;
                        }
                    }
                }
                if (toRemove.Any())
                {

                    int offset = 0;
                    for (int j = 0; j < toRemove.Count(); j++)
                    {
                           int index = toRemove[j];
                            prodList.RemoveAt(index - offset);
                            offset++;
                        //System.Diagnostics.Debug.WriteLine(index);
                    }
                }
                SearchResultViewModel viewModel = new SearchResultViewModel
                {
                    Products = prodList,
                    TechSpecFilterList = listFilterTechSpec,
                    TypeRangeFilterList = listFilterType
                };
                return View("SearchResult", viewModel);
            }
                
           
        }

        public ActionResult Compare(int product1Id = 0, int product2Id = 0)
        {
            if (product1Id == 0 || product2Id == 0)
            {
                // Pass in some error Message
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("CompareProduct", "CompareProduct", new { product1Id, product2Id });
            }
        }
    }
}

JooleStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <script src="https://kit.fontawesome.com/5d6d6a5d19.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="header">
        <a href="@Url.Action("Index", "Search")"><img src="~/Images/joole Logo.png" class="header__logo"></a>
        
        <!-- For this form to refer to specific pages, I think we need to refer to current url -->
        <form class="header__search" action="/Search/OnSearch" method="post">
            <select id="search-dropdown" name="search-dropdown">
                <option class="search__dropdown-list" value="Mechanical">Mechanical</option>
                <option class="search__dropdown-list" value="Electrical">Electrical</option>
                <option class="search__dropdown-list" value="Stationary">Stationary</option>
                <option class="search__dropdown-list" value="Furniture">Furniture</option>
            </select>
            <select id="subcategory" name="subcategory" style="width: 150px; height: 35px; color: black; background-color: white; border: none; border-radius: 5px;">
            </select>
            <button id="search-submit" type="submit">
                <i class="fas fa-search"></i>
            </button>
        </form>
        <div>
            @if (!string.IsNullOrEmpty(Session["ProfileImage"] as string))
            {
                <img src="~/Images/@Session["ProfileImage"]" class="header__user-image">
            } else
            {
                <div class="header__user-image"></div>
            }
        </div>
    </div>
    <div class="layout__container">
        @RenderBody()
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/search.js")
</body>
</html>